# Generated by Django 3.2.19 on 2024-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='goods_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名'),
        ),
    ]
