# Generated by Django 2.2.2 on 2024-03-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_message_isread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=32)),
                ('account', models.CharField(max_length=20)),
            ],
        ),
    ]
