# Generated by Django 3.2.19 on 2024-03-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.IntegerField(max_length=20),
        ),
    ]
